---

name: ai-prepare-env
description: 'Prepares the environment for ai agents'
# Prepares the environment for ai agents.
runs:
  using: composite
  steps:
    - name: 'Prepare project environment'
      uses: ./.github/actions/prepare-env
    # -----
    - name: 'Setup MCP servers'
      run: make setup-mcp
      shell: bash
    # -----
    - name: 'Build inverted index'
      run: go42x kwb build
      shell: bash
    # -----
    - name: 'Generate ai agent environment'
      env:
        CI: true
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        GITHUB_EVENT_PAYLOAD: ${{ toJSON(github.event) }}
        GITHUB_HEAD_REF: ${{ github.head_ref }}
        GITHUB_REF_NAME: ${{ github.ref_name }}
        GITHUB_SHA: ${{ github.sha }}
        GITHUB_SERVER_URL: ${{ github.server_url }}
        GITHUB_RUN_ID: ${{ github.run_id }}
      run: go42x agentenv generate
      shell: bash
